application: rodarmor-shipyard
version: 1
runtime: go
api_version: go1
default_expiration: "0d 0m"

handlers:
- url: /[0-9a-f]{16-64}/src/(.*)
  static_files: src/\1
  upload: src/.*
  expiration: "365d 0m"

- url: /src/(.*)
  static_files: src/\1
  upload: src/.*

- url: /.*
  script: _go_app
