application: rodarmor-shipyard
version: 1
runtime: go
api_version: go1
default_expiration: "0d 0m"

handlers:
- url: /(src|lib|build)/(.*)
  static_files: \1/\2
  upload: (src|lib|build)/.*
  application_readable: true

- url: /[0-9a-f]{10,64}/(src|lib|build)/(.*)
  static_files: \1/\2
  upload: (src|lib|build)/.*
  application_readable: true
  expiration: "365d 0m"

- url: /favicon.ico
  static_files: src/favicon.ico
  upload: src/favicon.ico

- url: /.*
  script: _go_app
